language: clojure
jdk:
  - oraclejdk8

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.lein
    - $HOME/.m2

script:
  - lein cljfmt check
  - lein test
  - lein uberjar

after_success:
  - CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) \
      -f target/coverage/codecov.json

notifications:
  email: false
  slack:
    secure: iGiHSXK67qp5MNqW5v6S9kpbKwTBc+O7elZZmwFuX0g4PwBPX+aBhtk69P3Otwm/9MVp7ZHBDtKdcBHrI0b7ikrTULf1k3DLRIdiUuz6ibIj0uV753CZUjqPOXVANpbdPFFQTT0PMieV3B21Dt1ypFfmQAEsepMPAnWR+WCD6YCcl1HHuoTjlALrch4k7Qkuvrk8LzCTcI971ltorMAUMI/skNYjWqFVyGp4PI0y34c372E6bZuGq4xWr7J09bbJferTIjtmZstaAJQEp67XangpnRtktY+Gsa6TtIPtyY0T5CD2DVJxAWzuyQoBkR4mVrZUcr7pbiOMRzM+Hdxm6ded9OYT2LKHIMoWEJjvo4vkZG/2prT3hWFGQEN82VrgDYezFrAE7vJZydiV3dDcckXvwBe3gSUcNkOHGLz8ztuFm9iaC4smSGoSzjd8CZt1/OGQsnko+zZnj/JNYOlrp7TKf/nzIX6q4tamYBU1SYwotBE5BzPo5dBR9b0bkq0+OUdDTQCAZkX6u0y1se0b7/JsvNS870/+Nq2NF+9Nh8lJGWxP1H7n7gJk8XVF+4op9eLNFs9lRyLqM4B91CkXU1eM49h5QQvU8NFay4IKSDRsKhnJEKnOUpR1mUpFklcRY65Rgg3HMXPuzhxHFvMQzLsHjydD7eqFOdxKfpTIfb4=
