language: clojure
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.lein
    - $HOME/.m2

script:
  - lein cljfmt check
  - lein test
  - lein uberjar

after_success:
  - CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) \
      -f target/coverage/codecov.json

notifications:
  email: false
