(* -*- mode: bison -*- *)

expr ::= eq | fn-call | ipv4-addr | identifier

identifier ::= #"[A-Za-z-]+"
maybe-whitespace ::= " "*

fn-call ::= identifier <"("> identifier <")">

eq ::= eqable ( <maybe-whitespace> <"="> <maybe-whitespace> eqable )+
<eqable> ::= fn-call | identifier | ipv4-addr

ipv4-addr ::= dec-byte <"."> dec-byte <"."> dec-byte <"."> dec-byte
<dec-byte> ::= #"25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?"
